/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mnuprg.calculadora.visao;

import br.com.mnuprg.calculadora.controle.CalculadoraController;
import br.com.mycompany.calculadora.enums.EnumOperacao;
import br.edu.telas.TelaInicial;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author ericr
 */
public class jFrTela extends javax.swing.JFrame {
    private CalculadoraController calculadoraController;
    private EnumOperacao ultimaOperacao;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jFrTela.class.getName());

    /**
     * Creates new form jFrTela
     */
    public jFrTela() {
        initComponents();
        getContentPane().setBackground(new Color(0,74,173));
        calculadoraController = new CalculadoraController();
        ultimaOperacao = EnumOperacao.SOMA;
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btAC = new javax.swing.JButton();
        btPARENTESE1 = new javax.swing.JButton();
        btPARENTESE2 = new javax.swing.JButton();
        btDIVIDIR = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btMULTIPLICAR = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btSUBTRAIR = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        brSOMAR = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btVIRGULA = new javax.swing.JButton();
        btFECHAR = new javax.swing.JButton();
        btIGUALDADE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setPreferredSize(new java.awt.Dimension(370, 500));

        tfValor.setEditable(false);
        tfValor.setBackground(new java.awt.Color(204, 204, 204));
        tfValor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        tfValor.setForeground(new java.awt.Color(0, 74, 173));
        tfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValor.setText("0,00");
        tfValor.setPreferredSize(new java.awt.Dimension(0, 0));
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 74, 173));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        btAC.setBackground(new java.awt.Color(255, 189, 89));
        btAC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAC.setForeground(new java.awt.Color(0, 74, 173));
        btAC.setText("AC");
        btAC.setPreferredSize(new java.awt.Dimension(90, 70));
        btAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btACActionPerformed(evt);
            }
        });
        jPanel1.add(btAC);

        btPARENTESE1.setBackground(new java.awt.Color(255, 189, 89));
        btPARENTESE1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btPARENTESE1.setForeground(new java.awt.Color(0, 74, 173));
        btPARENTESE1.setText("(");
        btPARENTESE1.setPreferredSize(new java.awt.Dimension(90, 70));
        btPARENTESE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPARENTESE1ActionPerformed(evt);
            }
        });
        jPanel1.add(btPARENTESE1);

        btPARENTESE2.setBackground(new java.awt.Color(255, 189, 89));
        btPARENTESE2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btPARENTESE2.setForeground(new java.awt.Color(0, 74, 173));
        btPARENTESE2.setText(")");
        btPARENTESE2.setPreferredSize(new java.awt.Dimension(90, 70));
        btPARENTESE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPARENTESE2ActionPerformed(evt);
            }
        });
        jPanel1.add(btPARENTESE2);

        btDIVIDIR.setBackground(new java.awt.Color(255, 189, 89));
        btDIVIDIR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDIVIDIR.setForeground(new java.awt.Color(0, 74, 173));
        btDIVIDIR.setText("/");
        btDIVIDIR.setPreferredSize(new java.awt.Dimension(90, 70));
        btDIVIDIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDIVIDIRActionPerformed(evt);
            }
        });
        jPanel1.add(btDIVIDIR);

        bt7.setBackground(new java.awt.Color(255, 189, 89));
        bt7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt7.setForeground(new java.awt.Color(0, 74, 173));
        bt7.setText("7");
        bt7.setPreferredSize(new java.awt.Dimension(90, 70));
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt7);

        bt8.setBackground(new java.awt.Color(255, 189, 89));
        bt8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt8.setForeground(new java.awt.Color(0, 74, 173));
        bt8.setText("8");
        bt8.setPreferredSize(new java.awt.Dimension(90, 70));
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt8);

        bt9.setBackground(new java.awt.Color(255, 189, 89));
        bt9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt9.setForeground(new java.awt.Color(0, 74, 173));
        bt9.setText("9");
        bt9.setPreferredSize(new java.awt.Dimension(90, 70));
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt9);

        btMULTIPLICAR.setBackground(new java.awt.Color(255, 189, 89));
        btMULTIPLICAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btMULTIPLICAR.setForeground(new java.awt.Color(0, 74, 173));
        btMULTIPLICAR.setText("*");
        btMULTIPLICAR.setPreferredSize(new java.awt.Dimension(90, 70));
        btMULTIPLICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMULTIPLICARActionPerformed(evt);
            }
        });
        jPanel1.add(btMULTIPLICAR);

        bt4.setBackground(new java.awt.Color(255, 189, 89));
        bt4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt4.setForeground(new java.awt.Color(0, 74, 173));
        bt4.setText("4");
        bt4.setPreferredSize(new java.awt.Dimension(90, 70));
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt4);

        bt5.setBackground(new java.awt.Color(255, 189, 89));
        bt5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt5.setForeground(new java.awt.Color(0, 74, 173));
        bt5.setText("5");
        bt5.setPreferredSize(new java.awt.Dimension(90, 70));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt5);

        bt6.setBackground(new java.awt.Color(255, 189, 89));
        bt6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt6.setForeground(new java.awt.Color(0, 74, 173));
        bt6.setText("6");
        bt6.setPreferredSize(new java.awt.Dimension(90, 70));
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt6);

        btSUBTRAIR.setBackground(new java.awt.Color(255, 189, 89));
        btSUBTRAIR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSUBTRAIR.setForeground(new java.awt.Color(0, 74, 173));
        btSUBTRAIR.setText("-");
        btSUBTRAIR.setPreferredSize(new java.awt.Dimension(90, 70));
        btSUBTRAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSUBTRAIRActionPerformed(evt);
            }
        });
        jPanel1.add(btSUBTRAIR);

        bt1.setBackground(new java.awt.Color(255, 189, 89));
        bt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 74, 173));
        bt1.setText("1");
        bt1.setPreferredSize(new java.awt.Dimension(90, 70));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1);

        bt2.setBackground(new java.awt.Color(255, 189, 89));
        bt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 74, 173));
        bt2.setText("2");
        bt2.setPreferredSize(new java.awt.Dimension(90, 70));
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2);

        bt3.setBackground(new java.awt.Color(255, 189, 89));
        bt3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 74, 173));
        bt3.setText("3");
        bt3.setPreferredSize(new java.awt.Dimension(90, 70));
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3);

        brSOMAR.setBackground(new java.awt.Color(255, 189, 89));
        brSOMAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        brSOMAR.setForeground(new java.awt.Color(0, 74, 173));
        brSOMAR.setText("+");
        brSOMAR.setPreferredSize(new java.awt.Dimension(90, 70));
        brSOMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brSOMARActionPerformed(evt);
            }
        });
        jPanel1.add(brSOMAR);

        bt0.setBackground(new java.awt.Color(255, 189, 89));
        bt0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt0.setForeground(new java.awt.Color(0, 74, 173));
        bt0.setText("0");
        bt0.setPreferredSize(new java.awt.Dimension(90, 70));
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel1.add(bt0);

        btVIRGULA.setBackground(new java.awt.Color(255, 189, 89));
        btVIRGULA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btVIRGULA.setForeground(new java.awt.Color(0, 74, 173));
        btVIRGULA.setText(",");
        btVIRGULA.setPreferredSize(new java.awt.Dimension(90, 70));
        btVIRGULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVIRGULAActionPerformed(evt);
            }
        });
        jPanel1.add(btVIRGULA);

        btFECHAR.setBackground(new java.awt.Color(255, 189, 89));
        btFECHAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFECHAR.setForeground(new java.awt.Color(0, 74, 173));
        btFECHAR.setText("VOLTAR");
        btFECHAR.setPreferredSize(new java.awt.Dimension(90, 70));
        btFECHAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFECHARActionPerformed(evt);
            }
        });
        jPanel1.add(btFECHAR);

        btIGUALDADE.setBackground(new java.awt.Color(255, 189, 89));
        btIGUALDADE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btIGUALDADE.setForeground(new java.awt.Color(0, 74, 173));
        btIGUALDADE.setText("=");
        btIGUALDADE.setPreferredSize(new java.awt.Dimension(90, 70));
        btIGUALDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIGUALDADEActionPerformed(evt);
            }
        });
        jPanel1.add(btIGUALDADE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(tfValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
    digita("2");   // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
    digita("5");   // TODO add your handling code here:
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
    digita("7");   // TODO add your handling code here:
    }//GEN-LAST:event_bt7ActionPerformed

    private void btACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btACActionPerformed
    limpa();   
    calculadoraController.zerar();
    }//GEN-LAST:event_btACActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
    digita("1");   // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
    digita("8");    // TODO add your handling code here:
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
    digita("9");    // TODO add your handling code here:
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
    digita("4");   // TODO add your handling code here:
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
    digita("6");   // TODO add your handling code here:
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
    digita("3");    // TODO add your handling code here:
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
    digita("0");    // TODO add your handling code here:
    }//GEN-LAST:event_bt0ActionPerformed

    private void btVIRGULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVIRGULAActionPerformed
    digita(",");    // TODO add your handling code here:
    }//GEN-LAST:event_btVIRGULAActionPerformed

    private void btFECHARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFECHARActionPerformed
    TelaInicial tela = new TelaInicial();
    tela.setVisible(true);
    dispose();
    }//GEN-LAST:event_btFECHARActionPerformed

    private void brSOMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brSOMARActionPerformed
    calculadoraController.realizaOperacao(ultimaOperacao, StringToDouble(tfValor.getText()));
    ultimaOperacao = EnumOperacao.SOMA;
    limpa();
    }//GEN-LAST:event_brSOMARActionPerformed

    private void btSUBTRAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSUBTRAIRActionPerformed
    calculadoraController.realizaOperacao(ultimaOperacao, StringToDouble(tfValor.getText()));
    ultimaOperacao = EnumOperacao.SUBTRACAO;
    limpa();
    }//GEN-LAST:event_btSUBTRAIRActionPerformed

    private void btMULTIPLICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMULTIPLICARActionPerformed
    calculadoraController.realizaOperacao(ultimaOperacao, StringToDouble(tfValor.getText()));
    ultimaOperacao = EnumOperacao.MULTIPLICACAO;
    limpa();
    }//GEN-LAST:event_btMULTIPLICARActionPerformed

    private void btDIVIDIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDIVIDIRActionPerformed
    calculadoraController.realizaOperacao(ultimaOperacao, StringToDouble(tfValor.getText()));
    ultimaOperacao = EnumOperacao.DIVISAO;
    limpa();
    }//GEN-LAST:event_btDIVIDIRActionPerformed

    private void btIGUALDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIGUALDADEActionPerformed
 Double resultado = calculadoraController.realizaOperacao(
                          ultimaOperacao, 
                          StringToDouble(tfValor.getText()));

    if (resultado == null) {                      // divisão por zero
        tfValor.setText("Não é possível dividir por 0");
        calculadoraController.zerar();            // opcional: reinicia
    } else {
        tfValor.setText(DoubleToString(resultado));
    }

    }//GEN-LAST:event_btIGUALDADEActionPerformed

    private void btPARENTESE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPARENTESE2ActionPerformed
    digita(")");
    }//GEN-LAST:event_btPARENTESE2ActionPerformed

    private void btPARENTESE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPARENTESE1ActionPerformed
                                             
    digita("("); 
                                                                               

        // TODO add your handling code here:
    }//GEN-LAST:event_btPARENTESE1ActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed
    private String DoubleToString(Double numero){
        if (numero != null){
            DecimalFormat formato = new DecimalFormat("##,###,###,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
            formato.setParseBigDecimal(true);
            return formato.format(numero);
        }
        return"";
    }
    
    private void limpa(){
        tfValor.setText("0,00");
    }
           
    private void digita(String caractere){
        if (tfValor.getText().equals("0,00")){
            tfValor.setText(caractere);
        } else{
            if(caractere.equals(",") && tfValor.getText().contains(",")){
            } else{
                tfValor.setText(tfValor.getText().concat(caractere));
            }
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brSOMAR;
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAC;
    private javax.swing.JButton btDIVIDIR;
    private javax.swing.JButton btFECHAR;
    private javax.swing.JButton btIGUALDADE;
    private javax.swing.JButton btMULTIPLICAR;
    private javax.swing.JButton btPARENTESE1;
    private javax.swing.JButton btPARENTESE2;
    private javax.swing.JButton btSUBTRAIR;
    private javax.swing.JButton btVIRGULA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
private Double StringToDouble(String numero){
    NumberFormat nf = NumberFormat.getInstance(new Locale("pt", "BR"));
    try {
        return nf.parse(numero).doubleValue();
    } catch (ParseException ex) {
        logger.warning("Erro ao converter string para double: " + ex.getMessage());
        return 0.0;
    }
}

}
